const dinos = [
    { Name: "Tyrannosaurus Rex", Description: "One of the most iconic carnivorous dinosaurs, known for its powerful jaws and small, useless arms. Lived in the Cretaceous period.", Diet: "Carnivore", Era: "Cretaceous", DangerLevel: 5 },
    { Name: "Velociraptor", Description: "Known for its intelligence and featured in the Jurassic Park franchise. A small, fast carnivore with a sickle-shaped retractable claw. Lived in the Cretaceous period.", Diet: "Carnivore", Era: "Cretaceous", DangerLevel: 4 },
    { Name: "Triceratops", Description: "A herbivorous dinosaur with three distinctive horns and a frill. Lived in the Cretaceous period.", Diet: "Herbivore", Era: "Cretaceous", DangerLevel: 2 },
    { Name: "Stegosaurus", Description: "Recognized for its plated back and spiked tail. A herbivore with a distinctive double row of plates along its back. Lived in the Jurassic period.", Diet: "Herbivore", Era: "Jurassic", DangerLevel: 2 },
    { Name: "Brachiosaurus", Description: "A massive, long-necked herbivore with longer front legs than hind legs. Lived in the Jurassic period.", Diet: "Herbivore", Era: "Jurassic", DangerLevel: 1 },
    { Name: "Spinosaurus", Description: "Possibly the largest carnivorous dinosaur, adapted for aquatic life. Had a sail-like structure on its back. Lived in the Cretaceous period.", Diet: "Carnivore", Era: "Cretaceous", DangerLevel: 5 },
    { Name: "Mosasaur", Description: "A marine reptile, not a dinosaur, but lived during the same period. Large aquatic predator with a streamlined body. Lived in the Cretaceous period.", Diet: "Carnivore", Era: "Cretaceous", DangerLevel: 4 },
    { Name: "Plesiosaur", Description: "Another marine reptile with a long neck and four paddle-like limbs. Lived in the Mesozoic era.", Diet: "Carnivore", Era: "Mesozoic", DangerLevel: 3 },
    { Name: "Giganotosaurus", Description: "A large, predatory dinosaur similar to Tyrannosaurus Rex. Lived in the Cretaceous period.", Diet: "Carnivore", Era: "Cretaceous", DangerLevel: 5 },
    { Name: "Quetzalcoatlus", Description: "A giant pterosaur, not a dinosaur, with an impressive wingspan. Lived in the Cretaceous period.", Diet: "Carnivore", Era: "Cretaceous", DangerLevel: 3 },
    { Name: "Diplodocus", Description: "Known for its long neck and tail. A massive herbivore that roamed during the Jurassic period.", Diet: "Herbivore", Era: "Jurassic", DangerLevel: 1 },
    { Name: "Allosaurus", Description: "The apex predator of late Jurassic North America. A large carnivore with a prominent head crest. Lived in the Jurassic period.", Diet: "Carnivore", Era: "Jurassic", DangerLevel: 4 },
    { Name: "Parasaurolophus", Description: "Famous for its elaborate cranial crest. A herbivorous dinosaur with a tube-like structure on its head. Lived in the Cretaceous period.", Diet: "Herbivore", Era: "Cretaceous", DangerLevel: 2 },
    { Name: "Brontosaurus", Description: "A massive sauropod dinosaur. Known for its long neck and tail. Lived in the Jurassic period.", Diet: "Herbivore", Era: "Jurassic", DangerLevel: 1 },
    { Name: "Archaeopteryx", Description: "Considered one of the first birds. A small carnivorous dinosaur with feathers. Lived in the Jurassic period.", Diet: "Carnivore", Era: "Jurassic", DangerLevel: 2 },
    { Name: "Iguanodon", Description: "A large herbivorous dinosaur with a thumb spike. Lived in the Cretaceous period.", Diet: "Herbivore", Era: "Cretaceous", DangerLevel: 1 },
    { Name: "Carnotaurus", Description: "Known for its distinctive horns above the eyes. A carnivorous dinosaur with a unique appearance. Lived in the Cretaceous period.", Diet: "Carnivore", Era: "Cretaceous", DangerLevel: 4 },
    { Name: "Ankylosaurus", Description: "Armored dinosaur with a club-like tail. A herbivore with thick bony plates for protection. Lived in the Cretaceous period.", Diet: "Herbivore", Era: "Cretaceous", DangerLevel: 3 },
    { Name: "Pachycephalosaurus", Description: "Known for its thick, dome-shaped skull. A herbivore with a bony dome on its head for head-butting. Lived in the Cretaceous period.", Diet: "Herbivore", Era: "Cretaceous", DangerLevel: 2 },
    { Name: "Dimorphodon", Description: "A small pterosaur with a long tail and large head crest. Lived in the Jurassic period.", Diet: "Carnivore", Era: "Jurassic", DangerLevel: 3 },
    { Name: "Therizinosaurus", Description: "Characterized by its long claws and herbivorous diet. A large, feathered dinosaur. Lived in the Cretaceous period.", Diet: "Herbivore", Era: "Cretaceous", DangerLevel: 3 },
    { Name: "Plateosaurus", Description: "A long-necked, herbivorous dinosaur from the Late Triassic. Lived in the Triassic period.", Diet: "Herbivore", Era: "Triassic", DangerLevel: 2 },
    { Name: "Corythosaurus", Description: "A duck-billed dinosaur known for its distinctive crest. A herbivore with a hollow crest on its head. Lived in the Cretaceous period.", Diet: "Herbivore", Era: "Cretaceous", DangerLevel: 2 },
    { Name: "Oviraptor", Description: "Named for its initially incorrect association with egg theft. An omnivorous dinosaur. Lived in the Cretaceous period.", Diet: "Omnivore", Era: "Cretaceous", DangerLevel: 2 },
    { Name: "Dilophosaurus", Description: "A carnivorous dinosaur with a pair of crests on its head. Lived in the Jurassic period.", Diet: "Carnivore", Era: "Jurassic", DangerLevel: 4 },
    { Name: "Troodon", Description: "Possessing a relatively large brain compared to other dinosaurs. A small carnivore with keen intelligence. Lived in the Cretaceous period.", Diet: "Carnivore", Era: "Cretaceous", DangerLevel: 4 },
    { Name: "Camarasaurus", Description: "A large sauropod dinosaur with a long neck. Lived in the Jurassic period.", Diet: "Herbivore", Era: "Jurassic", DangerLevel: 1 },
    { Name: "Maiasaura", Description: "Known for nesting sites and evidence of parental care. A herbivore that lived in the Cretaceous period.", Diet: "Herbivore", Era: "Cretaceous", DangerLevel: 1 },
    { Name: "Suchomimus", Description: "A spinosaurid dinosaur with a crocodile-like snout. A carnivore adapted for fishing. Lived in the Cretaceous period.", Diet: "Carnivore", Era: "Cretaceous", DangerLevel: 3 },
    { Name: "Deinonychus", Description: "A smaller cousin of Velociraptor, known for its deadly hunting tactics. Lived in the Cretaceous period.", Diet: "Carnivore", Era: "Cretaceous", DangerLevel: 4 },
    { Name: "Apatosaurus", Description: "A massive, long-necked herbivore with a whip-like tail. Lived in the Jurassic period.", Diet: "Herbivore", Era: "Jurassic", DangerLevel: 1 },
    { Name: "Brachylophosaurus", Description: "A duck-billed dinosaur with a distinctive, flat crest. Lived in the Cretaceous period.", Diet: "Herbivore", Era: "Cretaceous", DangerLevel: 2 },
    { Name: "Dreadnoughtus", Description: "A gigantic titanosaur with a long neck and tail. Lived in the Cretaceous period.", Diet: "Herbivore", Era: "Cretaceous", DangerLevel: 1 },
    { Name: "Carcharodontosaurus", Description: "A large carnivorous dinosaur with serrated teeth. Lived in the Cretaceous period.", Diet: "Carnivore", Era: "Cretaceous", DangerLevel: 5 }
]

module.exports = dinos